apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-techchallenge02
  labels:
    app: app-techchallenge02
spec:
  selector:
    matchLabels:
      app: app-techchallenge02
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: app-techchallenge02
    spec:
      containers:
        - name: techchallenge02
          image: 341161836869.dkr.ecr.us-east-1.amazonaws.com/app-techchallenge
          imagePullPolicy: Always
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          ports:
            - containerPort: 80
              name: app-port
          readinessProbe:
            httpGet:
              path: /health/ready
              port: app-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: app-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3