version: "3.4"

services:
  mongo-service:
    labels:
      kompose.service.type: LoadBalancer
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data_container:/data/db"
    networks:
      - fiap-network
  
  apitechchallenge01:
    image: techchallenge02
    ports:
      - "80:80"
    networks:
      - fiap-network
    depends_on:
      - "mongo-service"

volumes:
  mongodb_data_container:
    driver: local
   
networks:
  fiap-network:
    driver: bridge